export const ACTIONS = Object.freeze({
  GET_TOP_STORIES_IDS: 'GET_TOP_STORIES_IDS',
  GET_TOP_STORIES_IDS_SUCCESS: 'GET_TOP_STORIES_IDS_SUCCESS',
  GET_TOP_STORIES_IDS_FAILURE: 'GET_TOP_STORIES_IDS_FAILURE',
  GET_COMMENT: 'GET_COMMENT',
  GET_COMMENT_SUCCESS: 'GET_COMMENT_SUCCESS',
  GET_COMMENT_FAILURE: 'GET_COMMENT_FAILURE',
  GET_STORY: 'GET_STORY',
  GET_STORY_SUCCESS: 'GET_STORY_SUCCESS',
  GET_STORY_FAILURE: 'GET_STORY_FAILURE',
});

export const API = Object.freeze({
  URL: 'https://hacker-news.firebaseio.com/v0',
});